package(default_visibility = ["//visibility:private"])

cc_test(
    name = "converter_test",
    timeout = "long",
    srcs = [
        "converter_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "distance_test",
    timeout = "long",
    srcs = [
        "distance_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "filter_test",
    timeout = "long",
    srcs = [
        "filter_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_test",
    timeout = "long",
    srcs = [
        "phtree_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_test_const_values",
    timeout = "long",
    srcs = [
        "phtree_test_const_values.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_test_ptr_values",
    timeout = "long",
    srcs = [
        "phtree_test_ptr_values.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_test_unique_ptr_values",
    timeout = "long",
    srcs = [
        "phtree_test_unique_ptr_values.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_multimap_d_test_unique_ptr_values",
    timeout = "long",
    srcs = [
        "phtree_multimap_d_test_unique_ptr_values.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_d_test",
    timeout = "long",
    srcs = [
        "phtree_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_d_test_filter",
    timeout = "long",
    srcs = [
        "phtree_d_test_filter.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_box_d_test_filter",
    timeout = "long",
    srcs = [
        "phtree_box_d_test_filter.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_multimap_d_test_filter",
    timeout = "long",
    srcs = [
        "phtree_multimap_d_test_filter.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_d_test_copy_move",
    timeout = "long",
    srcs = [
        "phtree_d_test_copy_move.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_multimap_d_test_copy_move",
    timeout = "long",
    srcs = [
        "phtree_multimap_d_test_copy_move.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_d_test_custom_key",
    timeout = "long",
    srcs = [
        "phtree_d_test_custom_key.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_d_test_preprocessor",
    timeout = "long",
    srcs = [
        "phtree_d_test_preprocessor.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_multimap_d_test",
    timeout = "long",
    srcs = [
        "phtree_multimap_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_box_d_test_query_types",
    timeout = "long",
    srcs = [
        "phtree_box_d_test_query_types.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_box_d_test",
    timeout = "long",
    srcs = [
        "phtree_box_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_multimap_box_d_test",
    timeout = "long",
    srcs = [
        "phtree_multimap_box_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_f_test",
    timeout = "long",
    srcs = [
        "phtree_f_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_box_f_test",
    timeout = "long",
    srcs = [
        "phtree_box_f_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_test_issues",
    timeout = "long",
    srcs = [
        "phtree_test_issues.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_test_issue_142",
    timeout = "long",
    srcs = [
        "phtree_test_issue_142.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)
