package(default_visibility = ["//visibility:private"])

cc_library(
    name = "common",
    hdrs = [
        "b_plus_tree_base.h",
        "b_plus_tree_hash_map.h",
        "b_plus_tree_map.h",
        "b_plus_tree_multimap.h",
        "base_types.h",
        "bits.h",
        "bpt_fixed_vector.h",
        "bpt_priority_queue.h",
        "common.h",
        "debug_helper.h",
        "flat_array_map.h",
        "flat_sparse_map.h",
        "tree_stats.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
    ],
)
