package(default_visibility = ["//visibility:private"])

#cc_binary(
#    name = "b_plus_multimap_fuzzer",
#    srcs = [
#        "b_plus_multimap_fuzzer.cpp",
#    ],
#    linkstatic = True,
#    deps = [
#        "//:phtree",
#    ],
#)
