package(default_visibility = ["//visibility:private"])

cc_test(
    name = "base_types_test",
    timeout = "long",
    srcs = [
        "base_types_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "bits_test",
    timeout = "long",
    srcs = [
        "bits_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "common_test",
    timeout = "long",
    srcs = [
        "common_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "flat_array_map_test",
    timeout = "long",
    srcs = [
        "flat_array_map_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "b_priority_queue_test",
    timeout = "long",
    srcs = [
        "b_priority_queue_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "b_vector_test",
    timeout = "long",
    srcs = [
        "b_vector_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "b_plus_tree_hash_map_test",
    timeout = "long",
    srcs = [
        "b_plus_tree_hash_map_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "b_plus_tree_map_test",
    timeout = "long",
    srcs = [
        "b_plus_tree_map_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "b_plus_tree_multimap_test",
    timeout = "long",
    srcs = [
        "b_plus_tree_multimap_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "flat_sparse_map_test",
    timeout = "long",
    srcs = [
        "flat_sparse_map_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//:phtree",
        "@gtest//:gtest_main",
    ],
)
