name: Bazel build

on: [ push ]

jobs:
  build:
    name: Run bazel
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bazel
        uses: bazelbuild/setup-bazelisk@v2

      # This causes build failures
      #      - name: Mount bazel cache  # Optional
      #        uses: actions/cache@v3
      #        with:
      #          path: "~/.cache/bazel"
      #          key: bazel

      - name: Clang format
        shell: bash
        run: ./ci/linting/clang-format.sh

      - name: Bazel format
        shell: bash
        run: ./ci/linting/buildifier.sh

      - name: Build
        shell: bash
        run: bazel build ...

      - name: Test
        shell: bash
        run: bazel test ...

      - name: Test
        shell: bash
        run: bazel test //test:phtree_test --config=asan
