name: CMake Windows build

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hendrikmuhs/ccache-action@v1.2

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}\out

      - name: Configure CMake
        working-directory: ${{github.workspace}}\out
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -S ${{github.workspace}} -B ${{github.workspace}}\out -DPHTREE_BUILD_EXAMPLES=ON -DPHTREE_BUILD_TESTS=ON

      - name: Build
        working-directory: ${{github.workspace}}\out
        run: cmake --build . --config ${env:BUILD_TYPE} -j2

      - name: Test
        working-directory: ${{github.workspace}}\out
        run: ctest -C ${env:BUILD_TYPE}
